# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

        # Install Python Dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

        # Build App and Run Application Test
      - name: Build Application and Run unit Test
        run: python run.py & pytest
  deploy:

    runs-on: self-hosted
    steps:
      - name: pulling repo
        run: git clone https://github.com/recafe54/self_hosted_demo.git
      - name: checkout repo
        run: cd self_hosted_demo
      - name: Install Python 3.6
        run: sudo apt-get update & sudo apt-get install python3.6
      - name: Install dependencies
        run: sudo pip install -r requirements.txt
      - name: Deploy App
        run: sudo python main.py
